### ISSUE TITLE
Angabe von Hausnummernzusätzen fehlt und führt zur Auswahl der falschen Straße

### ISSUE THREAD

**Issue by slangenbach** [asciidisco/awb2ics#1]
Hi,

erstmal vielen Dank für den Generator, wird bei den meisten Usern sicherlich einwandfrei seine Dienste verrichten 👍 

Die AWB bietet auf ihrer Website einen separaten Input für Hausnummerzusätze (z.B. 1a) an, dieser fehlt leider hier. Das führt dazu das bei mir die falsche Straße ausgewählt wird und ich im generierten Kalender nur graue und braune Tonnen sehe. 

Wäre klasse wenn du Hausnummerzusätze noch als zusätzlichen Parameter einbauen könntest.

**Comment by asciidisco** [comment]
Ah, das war mir gar nicht bewusst, danke für den Hinweis.
Ich bin momentan etwas Land unter mit Arbeit, deswegen wird es wohl 1 bis 2 Wochen dauern, bis ich den Fix gemacht habe.

**Comment by asciidisco** [comment]
Die Weihnachtszeit hat den Fix gebracht, sorry für´s lange warten, aber ich hoffe jetzt funktioniert es  ;)

**Comment by slangenbach** [comment]
Perfekt, danke!
